export default [
  // 文件夹名，英文简写，英文全写，
  ['barcelona', 'Barcelona', 'Circuit de Barcelona-Catalunya'],
  ['brands_hatch', 'Brands Hatch', 'Brands Hatch Circuit'],
  ['hungaroring', 'Hungaroring', 'Hungaroring'],
  ['misano', 'Misano', 'Misano World Circuit'],
  ['monza', 'Monza', 'Monza Circuit'],
  ['nurburgring', 'Nürburgring', 'Nürburgring'],
  ['paul_ricard', 'Paul Ricard', 'Circuit Paul Ricard'],
  ['silverstone', 'Silverstone', 'Silverstone'],
  ['spa', 'Spa-Francorchamps', 'Circuit de Spa-Francorchamps'],
  ['valencia', 'Valencia', 'Circuit Ricardo Tormo Valencia'],
  ['zandvoort', 'Zandvoort', 'Circuit Zandvoort'],
  ['zolder', 'Zolder', 'Circuit Zolder'],
  ['nurburgring_24h', '24h Nürb', ' 24h Nürburgring'],
  ['imola', 'Imola', 'Autodromo Enzo e Dino Ferrari'],
  ['red_bull_ring', 'Red Bull Ring', 'Red Bull Ring'],
  ['oulton_park', 'Oulton Park', 'Oulton Park Circuit'],
  ['snetterton', 'Snetterton', 'Snetterton Circuit'],
  ['donington', 'Donington Park', 'Donington Park'],
  ['cota', 'COTA', 'Circuit of the Americas'],
  ['indianapolis', 'Indianapolis', 'Indianapolis Motor Speedway'],
  ['watkins_glen', 'Watkins Glen', 'Watkins Glen International'],
  ['mount_panorama', 'Mount Panorama', 'Mount Panorama Circuit'],
  ['laguna_seca', 'Laguna Seca', 'WeatherTech Raceway Laguna Seca'],
  ['suzuka', 'Suzuka', 'Suzuka Circuit'],
  ['kyalami', 'Kyalami', 'Kyalami Grand Prix Circuit'],
]
